DROP TABLE IF EXISTS TBL_EMPLOYEES;

CREATE TABLE TBL_EMPLOYEES (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  email VARCHAR(250) DEFAULT NULL
);

DROP TABLE IF EXISTS TBL_CLUB;

CREATE TABLE TBL_CLUB (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL
);

DROP TABLE IF EXISTS TBL_CATEGORY;

CREATE TABLE TBL_CATEGORY (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  weight_min FLOAT NOT NULL,
  weight_max FLOAT NOT NULL
);

CREATE TABLE TBL_JUDOKA (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  license VARCHAR(50) ,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  date_of_birth DATE NOT NULL,
  weight FLOAT NULL,
  gender CHAR (6) NOT NULL,
  id_category INT NULL,
  id_club INT NOT NULL
);

 ALTER TABLE TBL_JUDOKA
    ADD FOREIGN KEY (id_category)
    REFERENCES TBL_CATEGORY(id);

 ALTER TABLE TBL_JUDOKA
    ADD FOREIGN KEY (id_club)
    REFERENCES TBL_CLUB(id);