DROP TABLE IF EXISTS TBL_CLUB;

CREATE TABLE TBL_CLUB (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL
);

DROP TABLE IF EXISTS TBL_CATEGORY;

CREATE TABLE TBL_CATEGORY (
  cd_category CHAR(25)  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  year_min INT NOT NULL,
  year_max INT NOT NULL
);

CREATE TABLE TBL_JUDOKA (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  license VARCHAR(50) ,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  date_of_birth DATE NULL,
  weight FLOAT NULL,
  gender CHAR (6) NOT NULL,
  cd_category CHAR(25) NULL,
  id_club INT NOT NULL
);

 ALTER TABLE TBL_JUDOKA
    ADD FOREIGN KEY (cd_category)
    REFERENCES TBL_CATEGORY(cd_category);

 ALTER TABLE TBL_JUDOKA
    ADD FOREIGN KEY (id_club)
    REFERENCES TBL_CLUB(id);